import time

##
# Global
##

rule get_paths:
    input:
        bamsepath=expand("{bamsepath}", bamsepath=config['bamsepath']),
        parampath=expand("{parampath}", parampath=config['parampath']),
        logpath=expand("{logpath}", logpath=config['logpath'])

##
# Read trimming
##

rule trimming:
    input:
        read1="{projectpath}/0-Data/{run}/{sample}_1.fastq",
        read2="{projectpath}/0-Data/{run}/{sample}_2.fastq",
        trim="{projectpath}/2-Filtered/{run}/trim.txt"
    threads: 1
    output:
        read1="{projectpath}/2-Filtered/{run}/{sample}_1.fastq",
        read2="{projectpath}/2-Filtered/{run}/{sample}_2.fastq"
    params:
        mee=expand("{mee}", mee=config['mee'])
    shell:
        """
        echo "\tTrimming sample {wildcards.sample}" >> {rules.get_paths.input.logpath}
        echo "\tTrimming sample {wildcards.sample}"
        Rscript {rules.get_paths.input.bamsepath}/bin/bamse-filterandtrim.R -f {input.read1} -r {input.read2} -o {output.read1} -u {output.read2} -t {input.trim} -e {params.mee} >> {rules.get_paths.input.logpath}
        """
