##
# Global
##

rule get_paths:
    input:
        bamsepath=expand("{bamsepath}", bamsepath=config['bamsepath']),

##
# Error learning and dada2
##

rule dada2:
    input:
        dir="{projectpath}/3-Trimmed"
    threads: 40
    output:
        asvs="{projectpath}/ASVs.fasta",
        taxa="{projectpath}/ASV_taxa.txt",
        counts="{projectpath}/ASV_counts.txt"
    params:
        taxonomy=expand("{taxonomy}", taxonomy=config['taxonomy'])
    shell:
        """
        Rscript {rules.get_paths.input.bamsepath}/bin/bamse-dada2.R -d {input.dir} -t {params.taxonomy} -a {output.asvs} -c {output.counts} -x {output.taxa}
        """
