##
# Global
##

rule get_paths:
    input:
        bamsepath=expand("{bamsepath}", bamsepath=config['bamsepath']),
        parampath=expand("{parampath}", parampath=config['parampath']),
        logpath=expand("{logpath}", logpath=config['logpath'])
##
# Error learning and dada2
##

rule dada2a:
    input:
        dir="{projectpath}/2-Filtered/{run}"
    threads: 40
    output:
        rds="{projectpath}/3-DADA2/{run}.rds"
    params:
        overlap=expand("{overlap}", overlap=config['overlap'])
    shell:
        """
        mkdir -p {wildcards.projectpath}/3-DADA2
        Rscript {rules.get_paths.input.bamsepath}/bin/bamse-dada2a.R -i {input.dir} -o {output.rds} -v {params.overlap} -l {rules.get_paths.input.logpath}
        """
