##
# Global
##

rule get_paths:
    input:
        bamsepath=expand("{bamsepath}", bamsepath=config['bamsepath']),

##
# ASV match table generation
##

rule matching:
    input:
        fasta="{projectpath}/ASVs.fasta"
    threads: 40
    output:
        match="{projectpath}/5-LULU/ASV_match.txt"
    params:
    shell:
        """
        python {rules.get_paths.input.bamsepath}/bin/bamse-asvmatch.py -i {input.fasta} -o {output.match}
        """

##
# LULU algorithm
##

rule lulu:
    input:
        table="{projectpath}/ASV_counts.csv",
        match="{projectpath}/5-LULU/ASV_match.txt"
    threads: 1
    output:
        table="{projectpath}/ASV_counts.lulu.csv",
        map="{projectpath}/5-LULU/ASVs.lulu.txt"
    params:
    shell:
        """
        Rscript {rules.get_paths.input.bamsepath}/bin/bamse-lulu.R --i {input.table} --m {input.match} --o {output.table} --r {output.map}
        """

##
# LULU filering
##

rule lulufilter:
    input:
        asvs="{projectpath}/ASVs.fasta",
        lulu="{projectpath}/ASV_counts.lulu.csv"
    threads: 1
    output:
        asvs="{projectpath}/ASVs.lulu.fasta"
    params:
    shell:
        """
        sh {rules.get_paths.input.bamsepath}/bin/bamse-lulufilter.sh -i {input.asvs} -l {input.lulu} -o {output.asvs}
        """
