##
# Global
##

rule get_paths:
    input:
        bamsepath=expand("{bamsepath}", bamsepath=config['bamsepath']),

##
# ASV match table generation
##

rule matching:
    input:
        fasta="{projectpath}/ASVs.fasta"
    threads: 40
    output:
        match="{projectpath}/ASVs.match"
    params:
    shell:
        """
        python {rules.get_paths.input.bamsepath}/bin/bamse-asmatch.py -i {input.fasta} -o {output.match}
        """

##
# LULU algorithm
##

rule lulu:
    input:
        table="{projectpath}/ASV_count.txt"
        match="{projectpath}/ASVs_match.txt"
    threads: 40
    output:
        table="{projectpath}/ASV_count_lulu.txt"
    params:
    shell:
        """
        Rscipt {rules.get_paths.input.bamsepath}/bin/bamse-lulu.R --i {input.table} --m {input.match} --o {output.table}
        """

##
# LULU algorithm
##

rule lulufilter:
    input:
        asvs="{projectpath}/ASVs.fastq"
        lulu="{projectpath}/ASV_lulu_count.txt"
    threads: 40
    output:
        asvs="{projectpath}/ASVs_lulu.fastq"
    params:
    shell:
        """
        sh {rules.get_paths.input.bamsepath}/bin/bamse-lulufilter-sh -i {input.asvs} -l {input.lulu} -o {output.asvs}
        """
