##
# Global
##

rule get_paths:
    input:
        bamsepath=expand("{bamsepath}", bamsepath=config['bamsepath']),
        parampath=expand("{parampath}", parampath=config['parampath']),
        logpath=expand("{logpath}", logpath=config['logpath']),
        projectpath=expand("{projectpath}", projectpath=config['projectpath'])
##
# Maximum likelihood phylogenety generation
##

rule phylogeny:
    input:
        fasta="{projectpath}/ASVs.fasta"
    threads: 4
    output:
        alignment="{projectpath}/6-Phylogeny/ASVs.align.fasta",
        tree="{projectpath}/ASVs.tre"
    shell:
        """
        sh {rules.get_paths.input.bamsepath}/bin/bamse-phylogeny.sh -i {input.fasta} -a {output.alignment} -d {rules.get_paths.input.projectpath} -t {output.tree} -c {threads} >> {rules.get_paths.input.logpath}
        """
