##
# Global
##

rule get_paths:
    input:
        bamsepath=expand("{bamsepath}", bamsepath=config['bamsepath']),
        parampath=expand("{parampath}", parampath=config['parampath']),
        logpath=expand("{logpath}", logpath=config['logpath'])
##
# Error learning and dada2
##

rule dada2b:
    input:
        dir="{projectpath}/3-DADA2/"
    threads: 40
    output:
        asvs="{projectpath}/ASVs.fasta",
        taxa="{projectpath}/ASV_taxa.txt",
        counts="{projectpath}/ASV_counts.txt"
    params:
        taxonomy=expand("{taxonomy}", taxonomy=config['taxonomy'])
    shell:
        """
        Rscript {rules.get_paths.input.bamsepath}/bin/bamse-dada2b.R -d {input.dir} -t {params.taxonomy} -a {output.asvs} -c {output.counts} -x {output.taxa} -l {rules.get_paths.input.logpath}
        """
