##
# Global
##

rule get_paths:
    input:
        bamsepath=expand("{bamsepath}", bamsepath=config['bamsepath']),
        parampath=expand("{parampath}", parampath=config['parampath']),
        logpath=expand("{logpath}", logpath=config['logpath'])
##
# Optimal trimming of reads
##

rule optimaltrim:
    input:
        dir="{projectpath}/2-Filtered/{run}"
    threads: 1
    output:
        trim="{projectpath}/2-Filtered/{run}/trim.txt"
    params:
        pattern="csv"
    shell:
        """
        echo "\tComputing optimal trimming scores" >> {rules.get_paths.input.logpath}
        echo "\tComputing optimal trimming scores"
        Rscript {rules.get_paths.input.bamsepath}/bin/bamse-optimaltrim.R -i {input.dir} -o {output.trim} -p {rules.get_paths.input.parampath} -n {params.pattern} -l {rules.get_paths.input.logpath} 2>> /dev/null
        """
