import time

##
# Global
##

rule get_paths:
    input:
        bamsepath=expand("{bamsepath}", bamsepath=config['bamsepath']),
        parampath=expand("{parampath}", parampath=config['parampath']),
        logpath=expand("{logpath}", logpath=config['logpath'])

##
# Primer clipping
##

rule clip:
    input:
        read1="{projectpath}/0-Data/{run}/{sample}_1.fastq",
        read2="{projectpath}/0-Data/{run}/{sample}_2.fastq"
    threads: 1
    output:
        read1="{projectpath}/1-Primertrimmed/{run}/{sample}_1.fastq",
        read2="{projectpath}/1-Primertrimmed/{run}/{sample}_2.fastq"
    params:
        primer1=expand("{primer1}", primer1=config['primer1']),
        primer2=expand("{primer2}", primer2=config['primer2'])
    shell:
        """
        echo "\tClipping primers from {wildcards.sample}" >> {rules.get_paths.input.logpath}
        echo "\tClipping primers from {wildcards.sample}"
        mkdir -p {wildcards.projectpath}/1-Primertrimmed
        sh {rules.get_paths.input.bamsepath}/bin/bamse-primerclip.sh -a {input.read1} -b {input.read2} -c {output.read1} -d {output.read2} -f {params.primer1} -r {params.primer2} >> {rules.get_paths.input.logpath}
        """
